# Generated by Django 6.1.1 on 2026-09-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_initial_wallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], max_length=16)),
                ('display_name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('value', 'Value'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=16)),
                ('input_credits_per_1k_tokens', models.PositiveIntegerField()),
                ('output_credits_per_1k_tokens', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('provider', 'tier', 'display_name'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_id'), name='catalog_provider_model_id_unique'), models.CheckConstraint(condition=models.Q(('provider__in', ('openai', 'anthropic', 'google')), ('tier__in', ('value', 'standard', 'premium')), ('input_credits_per_1k_tokens__gt', 0), ('output_credits_per_1k_tokens__gt', 0)), name='catalog_provider_tier_prices_valid')],
            },
        ),
    ]
