# Generated by Django 6.1.1 on 2026-09-29 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_provisional_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('reply', models.TextField()),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('input_tokens_estimated', models.BooleanField(default=False)),
                ('output_tokens_estimated', models.BooleanField(default=False)),
                ('credits_charged', models.PositiveBigIntegerField()),
                ('mode', models.CharField(choices=[('mock', 'Mock'), ('real', 'Real')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='wallet_transaction_amount_matches_type',
        ),
        migrations.AddField(
            model_name='chatexchange',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='core.catalogmodel'),
        ),
        migrations.AddField(
            model_name='chatexchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='exchange',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_transaction', to='core.chatexchange'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('exchange__isnull', True), ('transaction_type__in', ('signup_bonus', 'top_up'))), models.Q(('amount__lt', 0), ('exchange__isnull', False), ('transaction_type', 'usage')), _connector='OR'), name='wallet_transaction_amount_matches_type'),
        ),
    ]
